<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 7 (Part 2)</b></center>    
<pre>

### Step 1: Load the Dataset
Load the `Tdata.csv` file and display the first few rows.

In [18]:
import pandas as pd
df = pd.read_csv("Tdata.csv")
df.head(5)

  Transaction  bread  butter  coffee  eggs  jam  milk
0          T1      1       1       0     0    0     1
1          T2      1       1       0     0    1     0
2          T3      1       0       0     1    0     1
3          T4      1       1       0     0    0     1
4          T5      1       0       1     0    0     0

### Step 2: Drop the 'Transaction' Column
We're only interested in the items (not the transaction IDs).

In [21]:
df_items = df.drop(columns = ['Transaction'])
df_items.head()

   bread  butter  coffee  eggs  jam  milk
0      1       1       0     0    0     1
1      1       1       0     0    1     0
2      1       0       0     1    0     1
3      1       1       0     0    0     1
4      1       0       1     0    0     0

### Step 3: Count Single Items
See how many transactions include each item.

In [24]:
df_items.sum()

bread     5
butter    3
coffee    2
eggs      2
jam       2
milk      3
dtype: int64

### Step 4: Define Apriori Function
This function finds frequent itemsets of size 1, 2, and 3 with minimum support.

In [27]:
from itertools import combinations
def AprioriFun(df, minSupport):
    n = len(df)
    result = []

    for i in [1,2,3]:
        for items in combinations(df.columns,i):
            mask = df[list(items)].all(axis = 1)
            support = mask.sum()/n
            print(f"{frozenset(items)}->{round(support,2)}")
            if support >= minSupport:
                result.append((frozenset(items),round(support,2)))
    
    return result

### Step 5: Run Apriori
Set `min_support = 0.6` and display the frequent itemsets.

In [30]:
frequent_itemsets = AprioriFun(df,minSupport = 0.5)

for itemset,support in frequent_itemsets:
    print(f"{set(itemset)}->support:{support}")

frozenset({'Transaction'})->1.0
frozenset({'bread'})->0.83
frozenset({'butter'})->0.5
frozenset({'coffee'})->0.33
frozenset({'eggs'})->0.33
frozenset({'jam'})->0.33
frozenset({'milk'})->0.5
frozenset({'Transaction', 'bread'})->0.83
frozenset({'Transaction', 'butter'})->0.5
frozenset({'Transaction', 'coffee'})->0.33
frozenset({'eggs', 'Transaction'})->0.33
frozenset({'Transaction', 'jam'})->0.33
frozenset({'Transaction', 'milk'})->0.5
frozenset({'butter', 'bread'})->0.5
frozenset({'bread', 'coffee'})->0.17
frozenset({'eggs', 'bread'})->0.17
frozenset({'jam', 'bread'})->0.17
frozenset({'bread', 'milk'})->0.5
frozenset({'butter', 'coffee'})->0.0
frozenset({'eggs', 'butter'})->0.0
frozenset({'butter', 'jam'})->0.17
frozenset({'butter', 'milk'})->0.33
frozenset({'eggs', 'coffee'})->0.17
frozenset({'jam', 'coffee'})->0.17
frozenset({'milk', 'coffee'})->0.0
frozenset({'eggs', 'jam'})->0.17
frozenset({'eggs', 'milk'})->0.17
frozenset({'jam', 'milk'})->0.0
frozenset({'Transaction', 'butter', 'bread'})->0.5
frozenset({'Transaction', 'bread', 'coffee'})->0.17
frozenset({'eggs', 'Transaction', 'bread'})->0.17
frozenset({'Transaction', 'jam', 'bread'})->0.17
frozenset({'Transaction', 'bread', 'milk'})->0.5
frozenset({'Transaction', 'butter', 'coffee'})->0.0
frozenset({'eggs', 'Transaction', 'butter'})->0.0
frozenset({'Transaction', 'butter', 'jam'})->0.17
frozenset({'Transaction', 'butter', 'milk'})->0.33
frozenset({'eggs', 'Transaction', 'coffee'})->0.17
frozenset({'Transaction', 'jam', 'coffee'})->0.17
frozenset({'Transaction', 'milk', 'coffee'})->0.0
frozenset({'eggs', 'Transaction', 'jam'})->0.17
frozenset({'eggs', 'Transaction', 'milk'})->0.17
frozenset({'Transaction', 'jam', 'milk'})->0.0
frozenset({'butter', 'bread', 'coffee'})->0.0
frozenset({'eggs', 'butter', 'bread'})->0.0
frozenset({'jam', 'butter', 'bread'})->0.17
frozenset({'butter', 'bread', 'milk'})->0.33
frozenset({'eggs', 'bread', 'coffee'})->0.0
frozenset({'jam', 'bread', 'coffee'})->0.0
frozenset({'milk', 'bread', 'coffee'})->0.0
frozenset({'eggs', 'jam', 'bread'})->0.0
frozenset({'eggs', 'bread', 'milk'})->0.17
frozenset({'jam', 'bread', 'milk'})->0.0
frozenset({'eggs', 'butter', 'coffee'})->0.0
frozenset({'butter', 'jam', 'coffee'})->0.0
frozenset({'milk', 'butter', 'coffee'})->0.0
frozenset({'eggs', 'butter', 'jam'})->0.0
frozenset({'eggs', 'butter', 'milk'})->0.0
frozenset({'butter', 'jam', 'milk'})->0.0
frozenset({'eggs', 'jam', 'coffee'})->0.17
frozenset({'eggs', 'milk', 'coffee'})->0.0
frozenset({'milk', 'jam', 'coffee'})->0.0
frozenset({'eggs', 'jam', 'milk'})->0.0
{'Transaction'}->support:1.0
{'bread'}->support:0.83
{'butter'}->support:0.5
{'milk'}->support:0.5
{'Transaction', 'bread'}->support:0.83
{'Transaction', 'butter'}->support:0.5
{'Transaction', 'milk'}->support:0.5
{'butter', 'bread'}->support:0.5
{'bread', 'milk'}->support:0.5
{'Transaction', 'butter', 'bread'}->support:0.5
{'Transaction', 'bread', 'milk'}->support:0.5

### Step 6 Display as a DataFrame

In [33]:
result_df = pd.DataFrame(frequent_itemsets,columns = ['Itemset','Support'])
result_df

                         Itemset  Support
0                  (Transaction)     1.00
1                        (bread)     0.83
2                       (butter)     0.50
3                         (milk)     0.50
4           (Transaction, bread)     0.83
5          (Transaction, butter)     0.50
6            (Transaction, milk)     0.50
7                (butter, bread)     0.50
8                  (bread, milk)     0.50
9   (Transaction, butter, bread)     0.50
10    (Transaction, bread, milk)     0.50

# Orange Tool : - >Generate Same Frequent Patterns in Orange tools

# Extra : - >  Define Apriori Function without itertools